"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.
"""

import os
from pathlib import Path

import dj_database_url

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv


# =========================================================
# BASE
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# =========================================================
# SEGURIDAD
# =========================================================

DEBUG = os.getenv(
    "DJANGO_DEBUG",
    "false",
).lower() in {
    "1",
    "true",
    "yes",
}

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "",
)

if (
    not SECRET_KEY
    or SECRET_KEY == "replace-with-a-generated-secret"
):
    raise ImproperlyConfigured(
        "Define DJANGO_SECRET_KEY en el entorno o en .env."
    )


ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        "localhost,127.0.0.1,[::1]",
    ).split(",")
    if host.strip()
]


CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "",
    ).split(",")
    if origin.strip()
]


SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG

SECURE_HSTS_SECONDS = (
    31536000
    if not DEBUG
    else 0
)

SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False


# =========================================================
# APLICACIONES
# =========================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",

    # Almacenamiento S3 compatible
    "storages",

    # Aplicaciones propias
    "products",
]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "config.urls"


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [
    {
        "BACKEND": (
            "django.template.backends.django."
            "DjangoTemplates"
        ),
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                (
                    "django.template.context_processors."
                    "request"
                ),
                (
                    "django.contrib.auth.context_processors."
                    "auth"
                ),
                (
                    "django.contrib.messages.context_processors."
                    "messages"
                ),
            ],
        },
    },
]


WSGI_APPLICATION = "config.wsgi.application"


# =========================================================
# BASE DE DATOS
# =========================================================

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "",
)


if DATABASE_URL:

    # Neon PostgreSQL
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }

else:

    # Fallback local
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# =========================================================
# VALIDACIÓN DE CONTRASEÑAS
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# =========================================================
# IDIOMA / ZONA HORARIA
# =========================================================

LANGUAGE_CODE = "es-cl"

TIME_ZONE = "America/Santiago"

USE_I18N = True

USE_TZ = True


# =========================================================
# ARCHIVOS ESTÁTICOS
# =========================================================

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"


# =========================================================
# NEON OBJECT STORAGE
# =========================================================

AWS_ACCESS_KEY_ID = os.getenv(
    "AWS_ACCESS_KEY_ID",
)

AWS_SECRET_ACCESS_KEY = os.getenv(
    "AWS_SECRET_ACCESS_KEY",
)

AWS_STORAGE_BUCKET_NAME = os.getenv(
    "AWS_STORAGE_BUCKET_NAME",
    "tcg-images",
)

AWS_S3_ENDPOINT_URL = os.getenv(
    "AWS_ENDPOINT_URL_S3",
)

AWS_S3_REGION_NAME = os.getenv(
    "AWS_REGION",
    "us-east-2",
)


# S3 Signature V4
AWS_S3_SIGNATURE_VERSION = "s3v4"


# No sobrescribir imágenes si tienen
# exactamente el mismo nombre.
AWS_S3_FILE_OVERWRITE = False


# No establecer ACL automáticamente.
AWS_DEFAULT_ACL = None


# =========================================================
# STORAGE DE DJANGO
# =========================================================

# Usaremos Neon Object Storage solamente cuando
# las credenciales necesarias estén configuradas.
#
# Esto permite que el proyecto siga funcionando
# localmente incluso si no configuramos S3.

USE_S3_STORAGE = all(
    [
        AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY,
        AWS_STORAGE_BUCKET_NAME,
        AWS_S3_ENDPOINT_URL,
    ]
)


if USE_S3_STORAGE:

    STORAGES = {

        # ---------------------------------------------
        # Imágenes / archivos subidos
        # ---------------------------------------------

        "default": {
            "BACKEND": (
                "storages.backends.s3.S3Storage"
            ),
            "OPTIONS": {
                "access_key": AWS_ACCESS_KEY_ID,
                "secret_key": AWS_SECRET_ACCESS_KEY,
                "bucket_name": (
                    AWS_STORAGE_BUCKET_NAME
                ),
                "endpoint_url": (
                    AWS_S3_ENDPOINT_URL
                ),
                "region_name": (
                    AWS_S3_REGION_NAME
                ),
                "signature_version": "s3v4",
                "default_acl": None,
                "file_overwrite": False,
            },
        },

        # ---------------------------------------------
        # CSS / JS
        # ---------------------------------------------

        "staticfiles": {
            "BACKEND": (
                "django.contrib.staticfiles.storage."
                "StaticFilesStorage"
            ),
        },
    }

else:

    # ---------------------------------------------
    # Desarrollo local sin S3
    # ---------------------------------------------

    MEDIA_URL = "/media/"

    MEDIA_ROOT = BASE_DIR / "media"

    STORAGES = {

        "default": {
            "BACKEND": (
                "django.core.files.storage."
                "FileSystemStorage"
            ),
        },

        "staticfiles": {
            "BACKEND": (
                "django.contrib.staticfiles.storage."
                "StaticFilesStorage"
            ),
        },
    }


# =========================================================
# PRIMARY KEY
# =========================================================

DEFAULT_AUTO_FIELD = (
    "django.db.models.BigAutoField"
)