# Generated by Django 5.2.17 on 2026-09-20 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcgdex_id', models.CharField(max_length=100, unique=True)),
                ('local_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('rarity', models.CharField(blank=True, max_length=100)),
                ('illustrator', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcgdex_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.card'),
        ),
        migrations.AddField(
            model_name='card',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='products.set'),
        ),
    ]
