# Generated by Django 5.2.17 on 2026-09-21 02:46

import django.core.validators
import django.db.models.deletion
import products.models
from decimal import Decimal
from uuid import uuid4
from django.db import migrations, models


def populate_skus(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    products = Product.objects.using(schema_editor.connection.alias)
    if products.filter(price__lt=0).exists():
        raise RuntimeError("Hay productos con precio negativo. Corrígelos antes de migrar; no se modificó su precio.")
    for product in products.all().iterator():
        products.filter(pk=product.pk).update(sku=f"TCG-{uuid4().hex.upper()}")


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_card_set_remove_product_name_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('unknown', 'Por definir'), ('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DMG', 'Dañada')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(choices=[('unknown', 'Por definir'), ('en', 'Inglés'), ('es', 'Español'), ('ja', 'Japonés'), ('other', 'Otro')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.RunPython(populate_skus, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=products.models.generate_sku, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('unknown', 'Por definir'), ('normal', 'Normal'), ('holo', 'Holo'), ('reverse', 'Reverse Holo'), ('other', 'Otra')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='products.set'),
        ),
        migrations.AlterField(
            model_name='product',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.card'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_price_nonnegative'),
        ),
    ]
