# Generated by Django 5.2.17 on 2026-09-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_condition_product_language_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='custom_image',
            field=models.ImageField(blank=True, null=True, upload_to='cards/'),
        ),
    ]
